# Generated by Django 5.2.8 on 2025-11-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(db_index=True, max_length=100)),
                ('time', models.DateTimeField()),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('major_name', models.CharField(max_length=100)),
                ('minor_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('employee_no', models.CharField(max_length=50)),
                ('picture_url', models.TextField()),
                ('raw_json', models.JSONField()),
                ('card_type', models.IntegerField(blank=True, null=True)),
                ('card_reader_no', models.IntegerField(blank=True, null=True)),
                ('door_no', models.IntegerField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('verify_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('mask', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['-time'], name='event_acces_time_942a83_idx'), models.Index(fields=['serial_no'], name='event_acces_serial__3c3432_idx'), models.Index(fields=['major', 'minor'], name='event_acces_major_fd9c66_idx')],
            },
        ),
    ]
