# Generated by Django 5.2.8 on 2025-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(unique=True)),
                ('time', models.DateTimeField()),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('major_name', models.CharField(blank=True, max_length=100, null=True)),
                ('minor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('employee_no', models.CharField(blank=True, max_length=50, null=True)),
                ('picture_url', models.TextField(blank=True, null=True)),
                ('raw_json', models.JSONField()),
            ],
        ),
    ]
