# Generated by Django 5.2.8 on 2025-12-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_accessevent_card_reader_no_and_more'),
        ('person', '0007_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.employee'),
        ),
    ]
