# Generated by Django 5.2.8 on 2025-12-19 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_accessevent_sent_to_telegram'),
        ('utils', '0006_telegramchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='utils.devices'),
        ),
    ]
