# Generated by Django 5.2.8 on 2025-12-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_accessevent_device'),
        ('utils', '0006_telegramchannel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessevent',
            unique_together={('device', 'serial_no')},
        ),
    ]
