# Generated by Django 5.2.8 on 2025-12-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_accessevent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='label_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
