# Generated by Django 5.2.8 on 2025-12-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_accessevent_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessevent',
            name='major',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='minor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
