# Generated by Django 5.2.8 on 2025-12-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='normal', max_length=50)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('door_right', models.CharField(default='1', max_length=50)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
