# Generated by Django 5.2.8 on 2025-12-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_begin_time_alter_person_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='face_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
