# Generated by Django 5.2.8 on 2025-12-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
        ('person', '0003_person_face_url_person_raw_json'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('employment', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=50)),
                ('salary', models.FloatField(default=0)),
                ('fine', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.branch')),
                ('break_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.breaktime')),
                ('day_off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.dayoff')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.shift')),
                ('work_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.workday')),
            ],
        ),
    ]
