# Generated by Django 5.2.8 on 2025-12-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employee_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person'),
        ),
    ]
