# Generated by Django 5.2.8 on 2025-12-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
        ('person', '0005_staff_employee_no_alter_staff_person'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='person',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='break_time',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='day_off',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='work_day',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('user_type', models.CharField(default='normal', max_length=50)),
                ('employment', models.CharField(blank=True, max_length=250, null=True)),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.FloatField(default=0)),
                ('fine', models.FloatField(default=0)),
                ('begin_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('door_right', models.CharField(default='1', max_length=50)),
                ('face_url', models.CharField(blank=True, max_length=500, null=True)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='faces/')),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.branch')),
                ('break_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.breaktime')),
                ('day_off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.dayoff')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.department')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.shift')),
                ('work_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.workday')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
