# Generated by Django 5.2.8 on 2025-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_remove_employee_user_employee_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_no',
            field=models.CharField(max_length=50),
        ),
    ]
