# Generated by Django 5.2.8 on 2025-12-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_accessevent_unique_together'),
        ('person', '0010_alter_employee_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('event_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='person.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_histories', to='event.accessevent')),
            ],
            options={
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['employee', 'event_date'], name='person_empl_employe_996c72_idx')],
            },
        ),
    ]
