# Generated by Django 5.2.8 on 2025-12-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_employeehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeehistory',
            name='label_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
