# Generated by Django 5.2.8 on 2025-12-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_accessevent_label_name'),
        ('person', '0012_employeehistory_label_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeehistory',
            name='person_empl_employe_996c72_idx',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='event_date',
        ),
        migrations.AddIndex(
            model_name='employeehistory',
            index=models.Index(fields=['employee'], name='person_empl_employe_d50472_idx'),
        ),
    ]
