# Generated by Django 5.2.8 on 2025-12-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_remove_employeehistory_person_empl_employe_996c72_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_fine',
            field=models.BooleanField(default=True),
        ),
    ]
