# Generated by Django 5.2.8 on 2025-12-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0003_alter_dayoff_days_alter_workday_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='break_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.breaktime'),
        ),
    ]
