# Generated by Django 5.2.8 on 2026-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0006_shift_approved_late_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='approved_late_min',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
