# Generated by Django 5.2.8 on 2026-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0006_shift_approved_late_min'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE "day_shift"
                        ALTER COLUMN "approved_late_min" TYPE integer
                        USING CASE
                            WHEN "approved_late_min" IS NULL THEN 15
                            ELSE (
                                EXTRACT(HOUR FROM "approved_late_min")::integer * 60 +
                                EXTRACT(MINUTE FROM "approved_late_min")::integer
                            )
                        END;
                        ALTER TABLE "day_shift" ALTER COLUMN "approved_late_min" SET NOT NULL;
                        ALTER TABLE "day_shift" ALTER COLUMN "approved_late_min" SET DEFAULT 15;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='shift',
                    name='approved_late_min',
                    field=models.PositiveIntegerField(default=15),
                ),
            ],
        ),
    ]