# Generated by Django 6.0 on 2025-12-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('s', 'superadmin'), ('a', 'admin')], max_length=10, null=True),
        ),
    ]
