# Generated by Django 5.2.8 on 2025-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_status',
            field=models.CharField(choices=[('p', 'paid'), ('np', 'not paid')], default='np', max_length=10),
        ),
    ]
