# Generated by Django 5.2.8 on 2025-12-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_status',
        ),
    ]
