# Generated by Django 5.2.8 on 2026-02-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('s', 'superadmin'), ('a', 'admin'), ('m', 'mahalla')], max_length=10, null=True),
        ),
    ]
