# Generated by Django 5.2.8 on 2025-12-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_branch_user_department_user_devices_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='ip',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
