# Generated by Django 5.2.8 on 2025-12-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_devices_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
