# Generated by Django 5.2.8 on 2025-12-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_employeehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeHistory',
        ),
    ]
