# Generated by Django 5.2.8 on 2025-12-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_telegramchannel_resolve_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramchannel',
            old_name='resolve_id',
            new_name='resolved_id',
        ),
    ]
