# Generated by Django 5.2.8 on 2025-12-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_alter_devices_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('go', 'Go'), ('plus', 'Plus')], max_length=20),
        ),
    ]
