# Generated by Django 5.2.8 on 2025-12-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_plan_description_alter_branch_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='plan',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
