# Generated by Django 5.2.8 on 2026-01-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_rename_name_plan_title_plan_content_plan_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.devices'),
        ),
    ]
