# Generated by Django 5.2.8 on 2026-01-28 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_branch_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.devices'),
        ),
    ]
