# Generated by Django 5.2.8 on 2025-12-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0015_alter_employee_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Ishda'), ('absent_excused', 'Sababli kelmadi'), ('absent_unexcused', 'Sababsiz kelmadi')], default='present', max_length=30)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('fine_amount', models.FloatField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
